config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :playdates
  devise_for :users
  resources :friends
  # get 'home/index'
  get 'home/about'
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/playdate.rb
class Playdate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to Edit this friend" if @friend.nil?
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :kids_names, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @playdates = Playdate.where(start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week)
  end
  def about
  end
end

app/controllers/playdates_controller.rb
class PlaydatesController < ApplicationController
  before_action :set_playdate, only: %i[ show edit update destroy ]

  # GET /playdates or /playdates.json
  def index
    @playdates = Playdate.all
  end

  # GET /playdates/1 or /playdates/1.json
  def show
  end

  # GET /playdates/new
  def new
    @playdate = Playdate.new
  end

  # GET /playdates/1/edit
  def edit
  end

  # POST /playdates or /playdates.json
  def create
    @playdate = Playdate.new(playdate_params)

    respond_to do |format|
      if @playdate.save
        format.html { redirect_to playdate_url(@playdate), notice: "Playdate was successfully created." }
        format.json { render :show, status: :created, location: @playdate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playdate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playdates/1 or /playdates/1.json
  def update
    respond_to do |format|
      if @playdate.update(playdate_params)
        format.html { redirect_to playdate_url(@playdate), notice: "Playdate was successfully updated." }
        format.json { render :show, status: :ok, location: @playdate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playdate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playdates/1 or /playdates/1.json
  def destroy
    @playdate.destroy

    respond_to do |format|
      format.html { redirect_to playdates_url, notice: "Playdate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playdate
      @playdate = Playdate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playdate_params
      params.require(:playdate).permit(:title, :description, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playdates_helper.rb
module PlaydatesHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
    <%= form.text_field :first_name,class: "form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
   
    <%= form.text_field :last_name, class: "form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :email, class: "form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
   
    <%= form.text_field :phone, class: "form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">   
    <%= form.text_field :kids_names, class: "form-control", placeholder: "Your Kids Names" %>
  </div>

  <div class="field form-group">   
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>


  </br>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Kids names:</strong>
    <%= friend.kids_names %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<%if user_signed_in?%>
  <table class="table table-striped table-bordered table-hover" >
    <thead class="thead-dark">
      <tr>
        <th>Name</th>        
        
        <th>Phone</th>
        <th>Kids Names</th>
        <th></th>
  
      </tr>
    </thead>


    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>       
            <td><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
            <td><%= friend.phone %></td>
            <td><%= friend.kids_names %></td>           
            <td><%= link_to 'Delete this friend', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          </tr>
        <%end%>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add New Friend', new_friend_path, class: "btn btn-primary" %>
<%else%>
  <h1>Hello!!!</h1>
<%end%>

app/views/friends/new.html.erb
<h1>Add a New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %> |
  <%= link_to "Back to friends", friends_path %>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
</div>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<div class="container mt-5 text-center>
    <h1>Hello Margo Friends</h1>
    <%= month_calendar(events: @playdates) do |date, playdates| %>
        <div class="day">
            <%= date.day %>
        </div>            
        <% playdates.each do |playdate| %> 
            <div class="day">   
                <div class="card-header">
                    <h6 class="card-title">
                        <%= link_to playdate.title, playdate %>
                    </h6>
                </div>                 
                <div class="card-footer">
                    <p class="card-text">
                        From <%= playdate.start_time.strftime('%R %p') %>                    
                        </br>
                        To <%= playdate.end_time.strftime('%R %p') %>
                    </p>
                </div>  
            </div>                
        <% end %>            
    <% end %>       
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-success">
  <div class="container-fluid">
    <%= link_to 'Margo', root_path,class:"navbar-brand" %>    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%=link_to 'About Us', home_about_path, class:"nav-link active" %>         
        </li>
        <li class="nav-item">
            <%=link_to 'Friends', friends_path, class:"nav-link active" %>         
        </li>
       
        <% if user_signed_in? %>
            <li class="nav-item">
                <%=link_to 'Sign Out',  destroy_user_session_path, method: :delete, class:"nav-link active" %>         
            </li>
            <li class="nav-item">
                <%=link_to 'Edit Profile', edit_user_registration_path, class:"nav-link active" %>         
            </li>
            <li class="nav-item">
                <%=link_to 'Add Friend', new_friend_path, class:"nav-link active" %>         
            </li>
        <%else%> 
            <li class="nav-item">
                <%=link_to 'Sign Up',  new_user_registration_path, class:"nav-link active" %>         
            </li>
            <li class="nav-item">
                <%=link_to 'Sign In', new_user_session_path, class:"nav-link active" %>         
            </li>
        <%end%>

    
    
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Margo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container"> 
    <br/>
      <%if notice %>
       <%= render 'layouts/alerts' %>
      <%end%>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

  </body>
</html>

app/views/playdates/_form.html.erb
<%= form_with(model: playdate) do |form| %>
  <% if playdate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(playdate.errors.count, "error") %> prohibited this playdate from being saved:</h2>

      <ul>
        <% playdate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/playdates/_playdate.html.erb
<div id="<%= dom_id playdate %>">
  <p>
    <strong>Title:</strong>
    <%= playdate.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= playdate.description %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= playdate.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= playdate.end_time %>
  </p>

</div>

app/views/playdates/edit.html.erb
<h1>Editing playdate</h1>

<%= render "form", playdate: @playdate %>

<br>

<div>
  <%= link_to "Show this playdate", @playdate %> |
  <%= link_to "Back to playdates", playdates_path %>
</div>

app/views/playdates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Playdates</h1>

<div id="playdates">
  <% @playdates.each do |playdate| %>
    <%= render playdate %>
    <p>
      <%= link_to "Show this playdate", playdate %>
    </p>
  <% end %>
</div>

<%= link_to "New playdate", new_playdate_path %>

app/views/playdates/new.html.erb
<h1>New playdate</h1>

<%= render "form", playdate: @playdate %>

<br>

<div>
  <%= link_to "Back to playdates", playdates_path %>
</div>

app/views/playdates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @playdate %>

<div>
  <%= link_to "Edit this playdate", edit_playdate_path(@playdate) %> |
  <%= link_to "Back to playdates", playdates_path %>

  <%= button_to "Destroy this playdate", @playdate, method: :delete %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>